/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */
import type { Components } from "@3dverse/livelink.core";
import { Entity as EntityBase } from "@livelink.base/scene/Entity";
import type { DefaultValue } from "@livelink.base/_prebuild/EntityComponents";
import { ComponentHandler } from "../sources/scene/ComponentHandler";
import { ComponentProxyCache } from "../sources/scene/ComponentProxyCache";

/**
 * Generated proxied component accessor layer for the browser {@link Entity}.
 *
 * Overrides the shared core's plain getters with Proxy-backed ones so nested mutations
 * (`entity.tags.value.push(...)`) flag the entity dirty. The setters are re-declared as-is:
 * an accessor override replaces the whole get/set pair, so a getter-only override would
 * shadow (and drop) the base setter.
 *
 * The proxies are cached per component so their reference identity survives re-renders. Headless
 * entities have no such layer: they hand out the raw stored values and carry no proxy state.
 *
 * @category Scene
 */
export abstract class EntityComponentsProxy extends EntityBase {
    /**
     * Stable component proxies handed out by the generated accessors.
     */
    readonly #component_proxies = new ComponentProxyCache();

{{componentAttributes}}
}
