/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */
import type { Components, ComponentName, ComponentType, EntityCore } from "@3dverse/livelink.core";
import { TypedEventTarget } from "../sources/TypedEventTarget";
import { EntityEvents } from "../sources/scene/EntityEvents";

/**
 * If specified as a component value, the default values will be applied.
 * Note that the component default values might change on future versions of their schema.
 *
 * @category Scene
 */
export type DefaultValue = "default";

/**
 * Storage core shared by every livelink client SDK entity with generated component accessor layer.
 * 
 * It owns the raw component record ({@link EntityCore}) and exposes the minimal protected primitives
 * to read/write it. It intentionally does NOT impose a component-access paradigm nor any entity
 * behaviour: the concrete {@link Entity} builds the public API (component accessors, dirty tracking,
 * scripts, …) on top of these primitives.
 * 
 * The generated component layer exposes one getter per component returning the live, mutable component object
 * stored on the paradigm-neutral. Reading a component returns the actual stored value, so it may be mutated in place;
 * mutations are not auto-detected — flag them explicitly with {@link Entity.updateComponent} / {@link Entity.updateComponents}. 
 * Use {@link Entity.deleteComponent} to remove a component. The generated layer also exposes one setter per component 
 * that delegates to the core's {@link Entity.updateComponent} & {@link Entity.deleteComponent}.
 * 
 * @category Scene
 */
export abstract class EntityComponents extends TypedEventTarget<EntityEvents> {
    /**
     * @internal
     */
    public static readonly component_names: Array<ComponentName> = [
{{componentNames}}
    ];

    /**
     *
     */
    #core: EntityCore;

    /**
     * @internal
     */
    get _core(): EntityCore {
        return this.#core;
    }

    /**
     *
     */
    get euid(): Readonly<Components.Euid> {
        return this.#core.euid;
    }

{{componentAttributes}}

    /**
     *
     */
    constructor({ euid }: { euid: Components.Euid }) {
        super();
        this.#core = { euid };
    }

    /**
     *
     */
    toJSON(): object {
        const { euid, ...components } = this.#core;
        return { euid: { value: euid.value }, ...components };
    }

    /**
     * @internal
     */
    protected _unsafeSetComponentValue<_ComponentName extends ComponentName>({
        component_name,
        value,
    }: {
        component_name: _ComponentName;
        value: ComponentType<_ComponentName> | undefined;
    }): void {
        //@ts-expect-error: sssh go back to sleep
        this.#core[component_name] = value;
    }

    /**
     * @internal
     */
    protected _unsafeGetComponentValue<_ComponentName extends ComponentName>({
        component_name,
    }: {
        component_name: _ComponentName;
    }): ComponentType<_ComponentName> | undefined {
        //@ts-expect-error: sssh go back to sleep
        return this.#core[component_name];
    }

    /**
     * @internal
     */
    protected abstract _setComponentValue<_ComponentName extends ComponentName>({
        component_name,
        value,
    }: {
        component_name: _ComponentName;
        value: Partial<ComponentType<_ComponentName>> | DefaultValue | undefined;
    }): void;
}
