/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    
    theme: {
        backgroundColor: {
            "color-ground": "hsl(var(--color-bg-ground-hsl), var(--tw-bg-opacity, 1))",
            "color-underground": "hsl(var(--color-bg-underground-hsl), var(--tw-bg-opacity, 1))",
            "color-overground": "hsl(var(--color-bg-overground-hsl), var(--tw-bg-opacity, 1))",
            "color-foreground": "hsl(var(--color-bg-foreground-hsl), var(--tw-bg-opacity, 1))",

            "color-accent": "hsl(var(--color-accent-500-hsl), var(--tw-bg-opacity, 1))",
            "color-accent-50": "var(--color-accent-50)",
            "color-accent-100": "var(--color-accent-100)",
            "color-accent-200": "var(--color-accent-200)",
            "color-accent-500": "var(--color-accent-500)",
            "color-accent-800": "var(--color-accent-800)",

            "color-informative-50": "var(--color-feedback-informative-50)",
            "color-informative-100": "var(--color-feedback-informative-100)",
            "color-informative-500": "var(--color-feedback-informative-500)",
            "color-informative": "var(--color-feedback-informative-500)",
            "color-informative-800": "var(--color-feedback-informative-800)",

            "color-positive-500": "var(--color-feedback-positive-500)",
            "color-positive": "var(--color-feedback-positive-500)",
            "color-positive-800": "var(--color-feedback-positive-800)",
            "color-positive-900": "var(--color-feedback-positive-900)",

            "color-warning-500": "var(--color-feedback-warning-500)",
            "color-warning": "var(--color-feedback-warning-500)",
            "color-warning-800": "var(--color-feedback-warning-800)",

            "color-negative-500": "var(--color-feedback-negative-500)",
            "color-negative": "var(--color-feedback-negative-500)",
            "color-negative-800": "var(--color-feedback-negative-800)",

            inherit: "inherit",
            current: "currentColor",
            transparent: "transparent",
        },
        colors: {
            "color-primary": "var(--color-content-primary)",
            "color-primary-dark": "var(--color-content-primary-dark)",
            "color-secondary": "var(--color-content-secondary)",
            "color-tertiary": "var(--color-content-tertiary)",
            "color-quaternary": "var(--color-content-quaternary)",

            "color-accent": "var(--color-accent-500)",
            "color-accent-50": "var(--color-accent-50)",
            "color-accent-100": "var(--color-accent-100)",
            "color-accent-200": "var(--color-accent-200)",
            "color-accent-500": "var(--color-accent-500)",
            "color-accent-800": "var(--color-accent-800)",

            "color-informative-50": "var(--color-feedback-informative-50)",
            "color-informative-100": "var(--color-feedback-informative-100)",
            "color-informative-500": "var(--color-feedback-informative-500)",
            "color-informative": "var(--color-feedback-informative-500)",
            "color-informative-800": "var(--color-feedback-informative-800)",

            "color-positive-500": "var(--color-feedback-positive-500)",
            "color-positive": "var(--color-feedback-positive-500)",
            "color-positive-800": "var(--color-feedback-positive-800)",
            "color-positive-900": "var(--color-feedback-positive-900)",

            "color-warning-500": "var(--color-feedback-warning-500)",
            "color-warning": "var(--color-feedback-warning-500)",
            "color-warning-800": "var(--color-feedback-warning-800)",

            "color-negative-400": "var(--color-feedback-negative-400)",
            "color-negative-500": "var(--color-feedback-negative-500)",
            "color-negative": "var(--color-feedback-negative-500)",
            "color-negative-800": "var(--color-feedback-negative-800)",
        },
        borderColor: {
            "color-accent": "var(--color-accent-500)",
            "color-accent-200": "var(--color-accent-200)",
            "color-accent-500": "var(--color-accent-500)",

            "color-primary": "var(--color-border-primary)",
            "color-secondary": "var(--color-border-secondary)",
            "color-tertiary": "var(--color-border-tertiary)",
            "color-quaternary": "var(--color-border-quaternary)",

            "color-informative-50": "var(--color-feedback-informative-50)",
            "color-informative-100": "var(--color-feedback-informative-100)",
            "color-informative-500": "var(--color-feedback-informative-500)",
            "color-informative": "var(--color-feedback-informative-500)",
            "color-informative-800": "var(--color-feedback-informative-800)",
            "color-informative-900": "var(--color-feedback-informative-900)",

            "color-positive-500": "var(--color-feedback-positive-500)",
            "color-positive": "var(--color-feedback-positive-500)",
            "color-positive-800": "var(--color-feedback-positive-800)",
            "color-positive-900": "var(--color-feedback-positive-900)",

            "color-warning-500": "var(--color-feedback-warning-500)",
            "color-warning": "var(--color-feedback-warning-500)",
            "color-warning-800": "var(--color-feedback-warning-800)",

            "color-negative-500": "var(--color-feedback-negative-500)",
            "color-negative": "var(--color-feedback-negative-500)",
            "color-negative-800": "var(--color-feedback-negative-800)",

            inherit: "inherit",
            current: "currentColor",
            transparent: "transparent",
        },
        fontFamily: {
            primary: "var(--font-family-primary)",
            secondary: "var(--font-family-secondary)",
        },
        fontSize: {
            base: ["var(--font-size-md)", "var(--leading-normal)"],
            "9xl": ["var(--font-size-9xl)", "var(--leading-normal)"],
            "8xl": ["var(--font-size-8xl)", "var(--leading-normal)"],
            "7xl": ["var(--font-size-7xl)", "var(--leading-normal)"],
            "6xl": ["var(--font-size-6xl)", "var(--leading-normal)"],
            "5xl": ["var(--font-size-5xl)", "var(--leading-normal)"],
            "4xl": ["var(--font-size-4xl)", "var(--leading-normal)"],
            "3xl": ["var(--font-size-3xl)", "var(--leading-snug)"],
            "2xl": ["var(--font-size-2xl)", "var(--leading-normal)"],
            xl: ["var(--font-size-xl)", "var(--leading-normal)"],
            lg: ["var(--font-size-lg)", "var(--leading-normal)"],
            md: ["var(--font-size-md)", "var(--leading-normal)"],
            sm: ["var(--font-size-sm)", "var(--leading-normal)"],
            xs: ["var(--font-size-xs)", "var(--leading-normal)"],
            "2xs": ["var(--font-size-2xs)", "var(--leading-normal)"],
            "3xs": ["var(--font-size-3xs)", "var(--leading-normal)"],
        },
        lineHeight: {
            3: "var(--leading-3)",
            4: "var(--leading-4)",
            5: "var(--leading-5)",
            6: "var(--leading-6)",
            7: "var(--leading-7)",
            8: "var(--leading-8)",
            9: "var(--leading-9)",
            10: "var(--leading-10)",
            none: "var(--leading-none)",
            tight: "var(--leading-tight)",
            snug: "var(--leading-snug)",
            normal: "var(--leading-normal)",
            relaxed: "var(--leading-relaxed)",
            loose: "var(--leading-loose)",
        },
        spacing: {
            0: "0",
            px: "1px",
            1: "var(--spacing-1)",
            2: "var(--spacing-2)",
            3: "var(--spacing-3)",
            4: "var(--spacing-4)",
            5: "var(--spacing-5)",
            6: "var(--spacing-6)",
            7: "var(--spacing-7)",
            8: "var(--spacing-8)",
            9: "var(--spacing-9)",
            10: "var(--spacing-10)",
            11: "var(--spacing-11)",
            12: "var(--spacing-12)",
            14: "var(--spacing-14)",
            16: "var(--spacing-16)",
            20: "var(--spacing-20)",
            24: "var(--spacing-24)",
            28: "var(--spacing-28)",
            32: "var(--spacing-32)",
            36: "var(--spacing-36)",
            40: "var(--spacing-40)",
            44: "var(--spacing-44)",
            48: "var(--spacing-48)",
            52: "var(--spacing-52)",
            56: "var(--spacing-56)",
            60: "var(--spacing-60)",
            64: "var(--spacing-64)",
            72: "var(--spacing-72)",
            80: "var(--spacing-80)",
            96: "var(--spacing-96)",
        },
        borderRadius: {
            sm: "var(--border-radius-sm)",
            md: "var(--border-radius-md)",
            lg: "var(--border-radius-lg)",
            xl: "var(--border-radius-xl)",

            full: "9999px",
            none: "0px",
            inherit: "inherit",
        },

        extend: {
            zIndex: {
                1: 1,
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
            },
            boxShadow: {
                sm: "var(--shadow-sm)",
                md: "var(--shadow-md)",
                lg: "var(--shadow-lg)",
                xl: "var(--shadow-xl)",
                "2xl": "var(--shadow-2xl)",
                "3xl": "var(--shadow-3xl)",
            },
            screens: {
                sm: "30em",
                md: "48em",
                lg: "62em",
                xl: "80em",
                "2xl": "96em",
                "3xl": "1600px",
                "4xl": "1800px",
            },
            keyframes: {},
        },
    },
    variants: {},
    plugins: [daisyui],
    corePlugins: {
        outline: false,
    },
    experimental: {
        optimizeUniversalDefaults: true,
    },
};
