/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */

import type { RTID, UUID, Quat, Vec3, Vec2, Int32, UInt32, Float, Int8} from "../../sources/types";
import type * as Assets from "./assets";

/**
 *
 */
export type ComponentType = keyof typeof ComponentHash;

/**
 *
 */
export type AssetRef<T> = UUID;

/**
 *
 */
export type EntityRef = {
    originalEUID: UUID;
    linkage: Array<UUID>;
};

/**
 *
 */
export type Euid = {
    value: UUID;
    rtid: RTID;
};

{{componentTypes}}

/**
 *
 */
export enum ComponentHash {
    {{componentHashes}}
};
