/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */
import type { Components } from "@3dverse/livelink.core";

/**
 *
 */
export type ComponentRecord = {
    {{componentAttributes}}
}
