/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */
import type { Components, ComponentName, RTID, UUID } from "@3dverse/livelink.core";

/**
 *
 */
export class EntityBase extends EventTarget {
    /**
     *
     */
    public static readonly component_names: Array<ComponentName> = [
{{componentNames}}
    ];

    /**
     *
     */
    readonly euid: Components.Euid;

{{componentAttributes}}

    /**
     * @internal
     */
    get rtid(): RTID {
        return this.euid.rtid;
    }

    /**
     * The UUID of the entity.
     *
     * Note that multiple entities can share the same UUID if they are different instances of the
     * same entity brought by multiple instances of the same scene.
     */
    get id(): UUID {
        return this.euid.value;
    }

    /**
     * The name of the entity.
     */
    get name(): string {
        return this.debug_name?.value ?? "<unnamed>";
    }

    /**
     *
     */
    protected _is_visible: boolean = true;

    /**
     *
     */
    constructor({ euid }: { euid: Components.Euid }) {
        super();
        this.euid = euid;
    }

    /**
     * @internal
     */
    toJSON(): Record<string, unknown> {
        const serialized: Record<string, unknown> = {};
        for (const p in this) {
            if (this._isSerializableComponent(p, this[p])) {
                serialized[p as string] = this[p];
            }
        }
        return serialized;
    }

    /**
     * @internal
     */
    public _isSerializableComponent(prop: PropertyKey, v: unknown): boolean {
        return (
            typeof prop === "string" &&
            v !== undefined &&
            prop[0] !== "_" &&
            EntityBase.component_names.includes(prop as ComponentName)
        );
    }
}
