/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */
import type { Components, ComponentName, ComponentType, RTID, UUID } from "@3dverse/livelink.core";

/**
 * If specified as a component value, the default values will be applied.
 * Note that the compponent default values might on future versions of their schema.
 */
export type DefaultValue = "default";

/**
 *
 */
export abstract class EntityBase extends EventTarget {
    /**
     * @internal
     */
    public static readonly component_names: Array<ComponentName> = [
{{componentNames}}
    ];

    /**
     *
     */
    readonly euid: Components.Euid;

{{componentAttributes}}

    /**
     * @internal
     */
    get rtid(): RTID {
        return this.euid.rtid;
    }

    /**
     * The UUID of the entity.
     *
     * Note that multiple entities can share the same UUID if they are different instances of the
     * same entity brought by multiple instances of the same scene.
     */
    get id(): UUID {
        return this.euid.value;
    }

    /**
     * The name of the entity.
     */
    get name(): string {
        return this.debug_name?.value ?? "<unnamed>";
    }

    /**
     *
     */
    protected _is_visible: boolean = true;

    /**
     *
     */
    constructor({ euid }: { euid: Components.Euid }) {
        super();
        this.euid = euid;
    }

    /**
     * Sets the value of a component. Used by the component setters.
     *
     * @internal
     */
    protected abstract _setComponentValue<_ComponentName extends ComponentName>({
        component_name,
        value,
    }: {
        component_name: _ComponentName;
        value: Partial<ComponentType<_ComponentName>> | DefaultValue | undefined;
    }): void;
}
