/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */

import type { UUID, Quat, Vec3, Vec2, Int32, UInt32, Float, Int8 } from "@livelink.core";

{{settingTypes}}
