/**
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file has been generated automatically from ftl-schemas
 */

import type { Settings } from "@3dverse/livelink.core";

/**
 *
 */
export class SettingsBase extends EventTarget {
    /**
     *
     */

{{settingsAttributes}}

}
